config/routes.rb
Rails.application.routes.draw do

  resources :items
  resources :users
  resources :categories
  resources :carts

  root 'items#index'

  get '/admin', :to => 'items#admin'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  patch '/checkout' => 'carts#checkout'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  belongs_to :item

  validates_presence_of :user_id, :item_id
  validates :quantity, numericality: { greater_than: 0 }
end

app/models/categories_item.rb
class CategoriesItem < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :items
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :carts
  has_many :users, through: :carts
	validates :title, :text, :price, :image, :quantity, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :carts
  has_many :items, through: :carts

  has_secure_password
  validates :name, :username, :email, :password, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #push
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include SessionsHelper
  include ApplicationHelper

  def new
    @item = Item.find(params[:item_id])
    p params
  end

  def create
    @cart = Cart.new(user_id: current_user.id, item_id: params[:item_id], quantity: params[:quantity])
    item = Item.find(params[:item_id])
    if has_enough_stock(params[:item_id], params[:quantity]) && @cart.save
      redirect_to user_path(current_user.id)
    else
      flash[:error] = "Please enter valid number between 1 and #{item.quantity}"
      redirect_to "/carts/new?item_id=#{params[:item_id]}"
    end
  end

  def checkout
    enough_stock = true
    @carts = current_user.carts.where(history: false)
    @total_price = current_user.carts.where(history: false).reduce(0) { |sum, cart| sum + cart.item.price * cart.quantity}.to_f
    current_user.carts.where(history: false).each do |cart|
      if !has_enough_stock(cart.item.id, cart.quantity)
        flash[:error] ||= []
        flash[:error] << "We currently do not have enough #{cart.item.title} in stock, please adjust your quantity according to our inventory."
        enough_stock = false
      end
    end
    p @carts
    if enough_stock
      current_user.carts.where(history: false).each do |cart|
        cart.history = true
        cart.item.quantity -= cart.quantity
        cart.save
        cart.item.save
      end
      render 'thankyou'
    else
      redirect_to user_path(current_user.id)
    end



  end

  def edit
    @cart = Cart.find(params[:id])
    @item = @cart.item
  end

  def update
    @cart = Cart.find(params[:id])
    @cart.quantity = params[:quantity]
    item = Item.find(params[:item_id])
    if has_enough_stock(params[:item_id], params[:quantity]) && @cart.save
      redirect_to user_path(current_user.id)
    else
      flash[:error] = "Please enter valid number between 1 and #{item.quantity}"
      redirect_to "/carts/#{@cart.id}/edit"
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    redirect_to user_path(current_user.id)

  end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/category_controller.rb
class CategoryController < ApplicationController

  def index
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]

  include SessionsHelper
  include ApplicationHelper

  def admin
    @items = Item.all
    if current_user && current_user.admin
      render "admin"
    else
      flash[:danger] = "Nice try, you're not an admin."
      redirect_to items_path
    end
  end

  def index
    @categories = Category.all
    @items = Item.all

  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @categories = Category.all
    # @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    categories = params[:item][:categories]

    if !categories.empty? && @item.save
      save_categories(categories)
      flash[:success] = "You have entered an item"
      redirect_to admin_path
    else
      flash[:danger] = "Wrong input"
      redirect_to new_item_path
    end
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def update

    @item = Item.find(params[:id])
    categories = params[:item][:categories]

    if !categories.empty? && @item.update(item_params)
      save_categories(categories)
      redirect_to admin_path
    else
      render 'edit'
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to admin_path
  end

  private
  def item_params
    params.require(:item).permit(:title, :text, :price, :image, :quantity)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  include SessionsHelper

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username].downcase)

    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      flash[:success] = 'You are logged in!'
      redirect_to items_path
    else
      flash[:danger] = 'Invalid username/password, please try again'
      redirect_to login_path
    end
  end

  def destroy
    log_out
    flash[:success] = 'You are logged out!'
    redirect_to items_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def show
    if current_user
      @user = current_user
      @total_price = @user.carts.where(history: false).reduce(0) { |sum, cart| sum + cart.item.price * cart.quantity}.to_f
    else
      redirect_to '/'
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      ExampleMailer.sample_email(@user).deliver

      flash[:success] = "Thank you for registering!"
      redirect_to items_path
    else
      flash[:danger] = "Please try again."
      redirect_to new_user_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :username, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def save_categories(categories)
    @item.categories = []
    categories.each do |cat_id|
      @item.categories << Category.find(cat_id)
    end
  end

  def has_enough_stock(item_id, quantity_request)
    Item.find(item_id).quantity >= quantity_request.to_i
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  # def admin
  #   if @user.email == "tim@tim.com"
  #     redirect_to admin_path
  #   end
  # end
end

app/views/carts/_form.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message

Stock:
=@item.quantity

= form_tag(carts_path, method: "post") do
  = label_tag(:quantity, "Quantity:")
  = text_field_tag(:quantity)
  %input{:name => "item_id", :type => "hidden", :value => @item.id}
  = submit_tag("Add to cart")

app/views/carts/edit.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message

Stock:
=@item.quantity

= form_tag(cart_path, method: "patch") do
  = label_tag(:quantity, "Quantity:")
  = text_field_tag(:quantity)
  %input{:name => "item_id", :type => "hidden", :value => @item.id}
  = submit_tag("Add to cart")

app/views/carts/new.html.haml
= render 'form'

app/views/carts/thankyou.html.haml
%h1 thank you you've purchased

-@carts.each do |cart|
  =cart.item.title
  %br
  =cart.quantity
  %br
  ="$#{cart.item.price * cart.quantity}"
  %br
Total:
=@total_price

app/views/categories/show.html.haml
%h1=@category.title
%br
-@category.items.each do |item|
  %h3=item.title
  %br

app/views/items/admin.html.haml
-if !current_user.admin
  YOU CANT ACCESS THIS PAGE
-else
  %div.navbar.navbar-inverse
    - flash.each do |message_type, message|
      %div.link{:class => "alert alert-#{message_type}"}= message
    %body
    %h1#title Inventory
    .link= link_to'New Item', new_item_path
    %div
      %table.table-compact
        %thead
          %tr
            %th.link-heading Item:
            %th.link-heading Image:
            %th.link-heading Description:
            %th.link-heading Price:
            %th.link-heading Quantity:
            %th.link-heading Category:
        - @items.each do |item|
          %tbody
            %tr
              %td.words-admin
                =item.title
              %td.words-admin
                =link_to image_tag("#{item.image}", width: "30%"), item_path(item.id)
              %td.words-admin
                =item.text
              %td.words-admin
                =number_to_currency(item.price)
              %td.words-admin
                =item.quantity
              %td.words-admin
                -item.categories.each do |cat|
                  =cat.title

              %td.words-admin
                = link_to 'Edit', edit_item_path(item)
              %td.words-admin
                = link_to 'Delete', item_path(item),
                method: :delete,
                data: { confirm: 'Are you sure?' }
    %p
    .words.navbar.navbar-inverse= link_to 'Home', root_path

app/views/items/edit.html.haml
%div.page
  %h1#title Edit Your Item
  = form_for @item, method: :patch do |f|
    - if @item.errors.any?
      #error_explanation
        %h2
          = pluralize(@item.errors.count, "error")
          prohibited
          this item from being saved:
        %ul
          - @item.errors.full_messages.each do |msg|
            %li= msg
    %p
      .words= f.label :title
      %br
        = f.text_field :title
    %p
      .words= f.label :text
      %br
        = f.text_area :text
    %p
      .words= f.label :quantity
      %br
        = f.text_area :quantity
    %p
      .words= f.label :price
      %br
        = f.text_field :price
    %p
      = f.label :categories
      %br
      - @categories.each do |cat|
        %input{:type => "checkbox", :name => "item[categories][]", :value => "#{cat.id}"}

        = f.label cat.title, class: "check_label"
    %p
      .words= f.label :image
      %br
        = f.text_area :image
    %p
      = f.submit
  .navbar.navbar-inverse= link_to 'Back', admin_path

app/views/items/index.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message


%div.page.navbar.navbar-inverse
  %body
  %h1#title Welcome to Your Online Shopping Paradise!
  %div
    %table.table.table-condensed
      %thead
        %tr
          %th.link-heading Recently Posted Items:
    %h2#title Categories:
    %div
      - @categories.each do |category|
        .words-admin.category-button.btn.btn-default= link_to category.title, category_path(category)

    - @items.each do |item|
      %div.col-sm-4
        %tbody
          %tr
            .link=item.title
            .link.img-responsive=link_to image_tag("#{item.image}", width: "50%"), item_path(item.id)
            %br
            -if item.quantity > 0
              %div.btn.btn-default
                =link_to "add to cart", {:controller => "carts", :action => "new", :item_id => item.id}
            -else
              %div.btn.btn-default.oos out of stock

            %br

app/views/items/new.html.haml
%div.page.navbar.navbar-inverse

  - flash.each do |message_type, message|
    %div{:class => "alert alert-#{message_type}"}= message

  %div.words
    %h2 Enter Your New Item:
    = form_for :item, url: items_path do |f|
      %p
        = f.label :Item
        .form-text= f.text_field :title
      %p
        = f.label :Description
        .form-text= f.text_field :text
      %p
        = f.label :Quantity
        .form-text= f.text_field :quantity
      %p
        = f.label :Price
        .form-text= f.text_field :price
      %p
        = f.label :categories
        %br
        - @categories.each do |cat|
          %input{:type => "checkbox", :name => "item[categories][]", :value => "#{cat.id}"}
          = f.label cat.title, class: "check_label"

      %p
        = f.label :image
        .form-text= f.text_field :image
      %p.form-text
        = f.submit

app/views/items/show.html.haml
%div.page.navbar.navbar-inverse
  %h1

  %h1.link= @item.title
  %br
  .words= "Item Details:"
  .words= @item.text
  %br
  .words= "Stock Quantity:"
  .words= @item.quantity
  %br
  .words= "Unit Price"
  .words= number_to_currency(@item.price)
  %br
  %img{:src => "#{@item.image}", :style => "width: auto;"}

app/views/layouts/application.html.haml
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shoppe
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:crossorigin => "anonymous", :href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", :integrity => "sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7", :rel => "stylesheet"}
    = stylesheet_link_tag    'application', media: 'all'
  %body
    %div.home-link
      =link_to 'Home', root_path
    -if logged_in? && current_user.admin
      =link_to 'Logout', logout_path, method: :delete
      =link_to 'Admin Page', admin_path
      %div.nav-cart
        =link_to 'My Cart', user_path(current_user.id)
    -elsif logged_in?
      =link_to 'Logout', logout_path, method: :delete
      %div.nav-cart
        =link_to 'My Cart', user_path(current_user.id)
    -else
      =link_to 'Register', new_user_path
      |
      =link_to 'Login', login_path

    = yield

app/views/users/new.html.haml
- flash.each do |message_type, message|
  %div{:class => "alert alert-#{message_type}"}= message

- provide(:title, 'Sign up')
%h1 Sign up
%div.register
  = form_for  :user, url: users_path do |f|
    %p
    = f.label :name
    = f.text_field :name
    %p
    = f.label :email
    = f.email_field :email
    %p
    = f.label :username
    = f.text_field :username
    %p
    = f.label :password
    = f.password_field :password
    %p
    = f.submit "Create my account", class: "btn btn-primary"

app/views/users/show.html.haml
-if flash[:error]
  - flash[:error].each do |message|
    %div{:class => "alert alert-error"}= message

%h1="This is #{current_user.name}'s cart!"
%h2 I have
-@user.carts.where(history: false).each do |cart|
  =cart.item.title
  %br
  Quantity in cart:
  =cart.quantity
  Stock:
  =cart.item.quantity
  Price:
  ="$#{cart.item.price * cart.quantity}"
  %br

  %td.words-admin
    = link_to 'Edit', edit_cart_path(cart)
  %td.words-admin
    = link_to 'Delete', cart_path(cart),
    method: :delete,
    data: { confirm: 'Are you sure?' }
  %br

Total Price:
="$#{@total_price}"
%br
= form_tag(checkout_path, method: "patch") do
  = submit_tag "Checkout", data: { confirm: "Are you sure?" }

%h2 History
-@user.carts.where(history: true).each do |cart|
  =cart.item.title
  %br
  Quantity:
  =cart.quantity
  %br